# Generated by Django 3.1.4 on 2021-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelfeatures',
            name='panel_version',
            field=models.CharField(max_length=50),
        ),
    ]
