# Generated by Django 3.1.4 on 2021-06-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0002_auto_20210518_1325'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalindication',
            name='clinical_in_version_6ddffd_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalindicationpanels',
            name='clinical_in_clinica_9b5ae9_idx',
        ),
        migrations.RemoveField(
            model_name='clinicalindication',
            name='version',
        ),
        migrations.AddField(
            model_name='clinicalindicationpanels',
            name='ci_version',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panelapp_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='panelfeatures',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='clinicalindicationpanels',
            index=models.Index(fields=['clinical_indication', 'panel', 'ci_version'], name='clinical_in_clinica_6cfee4_idx'),
        ),
    ]
