# Generated by Django 3.1.4 on 2021-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0003_auto_20210625_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalindication',
            old_name='clinical_indication_id',
            new_name='code',
        ),
    ]
